apiVersion: batch/v1
kind: CronJob
metadata:
  name: print-date-cronjob
spec:
  schedule: "*/1 * * * *"  # Every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: print-date-container
            image: busybox
            command: ["sh", "-c", "echo The date is $(date)"]
          restartPolicy: OnFailure # Only restart if it fails