apiVersion: batch/v1
kind: Job
metadata:
  name: print-date-job
spec:
  template:
    spec:
      containers:
      - name: print-date-container
        image: busybox
        command: ["sh", "-c", "echo The date is $(date)"]
      restartPolicy: Never