apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None  # Headless Service
  selector:
    app: mysql # Selects Pods with label app=mysql
  ports:
    - port: 3306
      name: mysql