apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-backend
  namespace: lms-app-namespace
spec:
  selector:
    matchLabels:
      app: lms-backend
  template: 
    metadata:
      labels:
        app: lms-backend
    spec:
      containers:
      - name: lms-backend-container
        image: mamun12/lms-backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: lms-backend-config

---
apiVersion: v1
kind: Service
metadata:
  name: lms-backend-service
  namespace: lms-app-namespace
spec:
  selector:
    app: lms-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32000
  type: NodePort