apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-frontend
  namespace: lms-app-namespace
spec:
  selector:
    matchLabels:
      app: lms-frontend
  template:
    metadata:
      labels:
        app: lms-frontend
    spec:
      containers:
      - name: lms-frontend-container
        image: mamun12/lms-frontend:latest
        ports:
        - containerPort: 3000