apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lms-pvc
  namespace: lms-app-namespace
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-database
  namespace: lms-app-namespace
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:8.2.2
        ports:
        - containerPort: 27017
        volumeMounts:
