apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lms-pvc
  namespace: lms-app-namespace
spec:
  resources:
    requests:
      storage: <Size>
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
