apiVersion: v1
kind: Namespace
metadata:
  name: dev-team
  labels:
    environment: production
    team: devops  
spec:
  hard: 
    pods: "10"
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi