apiVersion: v1
kind: Pod
metadata:
  name: host_val-pod
spec:
  containers:
    - name: host_vol-container
      image: nginx
      # Mount the hostPath volume
      volumeMounts:
        - name: host-vol
          mountPath: /usr/share/nginx/html
  # Define the hostPath volume
  volumes:
    - name: host-vol
      hostPath: 
         path:  /tmp/hostdata
         type: DirectoryOrCreate