apiVersion: v1
kind: Pod
metadata:
  name: resource-demo-pod
spec:
  containers:
    - name: resource-demo-container
      image: nginx:latest
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "500m"