apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: dolys36wm
  CLOUDINARY_API_KEY: "372395973228638"
  CLOUDINARY_API_SECRET: TVo7BxXM5rxCkSawMsG9Rdq4D5w
